const CACHE_NAME = "hanako-room-ops-v187";
const PERSISTENT_CACHES = new Set([CACHE_NAME, "hanako-private-photo-previews-v1"]);
const APP_SHELL = [
  "./",
  "./index.html",
  "./styles.css?v=187",
  "./app.js?v=187",
  "./cloud-sync.js?v=187",
  "./ops-engine.js?v=187",
  "./ops-phase2-engine.js?v=187",
  "./ops-phase3-engine.js?v=187",
  "./ops-phase4-engine.js?v=187",
  "./room-review-generator.js?v=187",
  "./version.json",
  "./update.html",
  "./covers/rakuten-room-cover-hanako-v5.jpg",
  "./icons/fashion-hanako-kawaisa-lab-logo.svg",
  "./icons/home-action-ai.svg",
  "./icons/home-action-room.svg",
  "./icons/home-action-coordinate.svg",
  "./icons/home-action-learning.svg",
  "./icons/home-toggle-open.svg",
  "./icons/home-toggle-close.svg",
  "./manifest.webmanifest",
  "./manifest-cafe.webmanifest",
  "./manifest-chic.webmanifest",
  "./manifest-lavender.webmanifest",
  "./manifest-mint.webmanifest",
  "./manifest-navy.webmanifest",
  "./manifest-strawberry.webmanifest",
  "./manifest-lemon.webmanifest",
  "./manifest-aqua.webmanifest",
  "./manifest-classic.webmanifest",
  "./manifest-office.webmanifest",
  "./manifest-oshikatsu.webmanifest",
  "./manifest-campus.webmanifest",
  "./manifest-rainy.webmanifest",
  "./manifest-sakura.webmanifest",
  "./manifest-marine.webmanifest",
  "./manifest-autumn.webmanifest",
  "./manifest-winter.webmanifest",
  "./manifest-beauty.webmanifest",
  "./manifest-travelgirl.webmanifest",
  "./manifest-sporty.webmanifest",
  "./manifest-evening.webmanifest",
  "./manifest-chocolate.webmanifest",
  "./manifest-florist.webmanifest",
  "./manifest-music.webmanifest",
  "./manifest-denim.webmanifest",
  "./manifest-museum.webmanifest",
  "./manifest-bakery.webmanifest",
  "./manifest-resort.webmanifest",
  "./manifest-studynight.webmanifest",
  "./manifest-wamodern.webmanifest",
  "./manifest-holiday.webmanifest",
  "./manifest-perfume.webmanifest",
  "./manifest-closet.webmanifest",
  "./manifest-shopping.webmanifest",
  "./manifest-mirror.webmanifest",
  "./manifest-notebook.webmanifest",
  "./manifest-heels.webmanifest",
  "./manifest-jewelry.webmanifest",
  "./manifest-teatime.webmanifest",
  "./manifest-bouquet.webmanifest",
  "./manifest-smartphone.webmanifest",
  "./manifest-parasol.webmanifest",
  "./manifest-sewing.webmanifest",
  "./manifest-camera.webmanifest",
  "./manifest-sunhat.webmanifest",
  "./manifest-dessert.webmanifest",
  "./manifest-parisienne.webmanifest",
  "./manifest-picnic.webmanifest",
  "./manifest-balletcore.webmanifest",
  "./manifest-cinema.webmanifest",
  "./manifest-ceramics.webmanifest",
  "./manifest-gardening.webmanifest",
  "./manifest-library.webmanifest",
  "./manifest-seaside.webmanifest",
  "./manifest-nightout.webmanifest",
  "./manifest-ribbonlady.webmanifest",
  "./manifest-vanitytray.webmanifest",
  "./manifest-maryjanes.webmanifest",
  "./manifest-ribboncardigan.webmanifest",
  "./manifest-cafeplate.webmanifest",
  "./manifest-charmbracelet.webmanifest",
  "./manifest-royalgala.webmanifest",
  "./manifest-yozakura.webmanifest",
  "./manifest-moonlight.webmanifest",
  "./manifest-anniversaryrose.webmanifest",
  "./manifest-jewelprincess.webmanifest",
  "./manifest-colorpalette.webmanifest",
  "./manifest-wardrobeaudit.webmanifest",
  "./manifest-fitcheck.webmanifest",
  "./manifest-shoeclinic.webmanifest",
  "./manifest-accessorylab.webmanifest",
  "./manifest-salehunter.webmanifest",
  "./manifest-layering.webmanifest",
  "./manifest-formalguest.webmanifest",
  "./manifest-streetstyle.webmanifest",
  "./manifest-creatorstudio.webmanifest",
  "./manifest-ribbonmannequin.webmanifest",
  "./manifest-styletablet.webmanifest",
  "./manifest-magazinestack.webmanifest",
  "./manifest-jewelhanger.webmanifest",
  "./manifest-coordboard.webmanifest",
  "./manifest-wavebalance.webmanifest",
  "./manifest-petitebalance.webmanifest",
  "./manifest-fabricexpert.webmanifest",
  "./manifest-bagstylist.webmanifest",
  "./manifest-travelpacking.webmanifest",
  "./manifest-photoangle.webmanifest",
  "./manifest-temperature.webmanifest",
  "./manifest-datestyle.webmanifest",
  "./manifest-fabriccare.webmanifest",
  "./manifest-trendcheck.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/hanako-avatar.jpg",
  "./icons/hanako-avatar-cafe.png",
  "./icons/hanako-avatar-chic.png",
  "./icons/hanako-avatar-lavender.png",
  "./icons/icon-cafe-192.png",
  "./icons/icon-cafe-512.png",
  "./icons/icon-chic-192.png",
  "./icons/icon-chic-512.png",
  "./icons/icon-lavender-192.png",
  "./icons/icon-lavender-512.png",
  "./icons/hanako-avatar-mint.png",
  "./icons/hanako-avatar-navy.png",
  "./icons/hanako-avatar-strawberry.png",
  "./icons/hanako-avatar-lemon.png",
  "./icons/hanako-avatar-aqua.png",
  "./icons/hanako-avatar-classic.png",
  "./icons/hanako-avatar-office.png",
  "./icons/hanako-avatar-oshikatsu.png",
  "./icons/hanako-avatar-campus.png",
  "./icons/hanako-avatar-rainy.png",
  "./icons/hanako-avatar-sakura.png",
  "./icons/hanako-avatar-marine.png",
  "./icons/hanako-avatar-autumn.png",
  "./icons/hanako-avatar-winter.png",
  "./icons/hanako-avatar-beauty.png",
  "./icons/hanako-avatar-travelgirl.png",
  "./icons/hanako-avatar-sporty.png",
  "./icons/hanako-avatar-evening.png",
  "./icons/hanako-avatar-chocolate.png",
  "./icons/hanako-avatar-florist.png",
  "./icons/hanako-avatar-music.png",
  "./icons/hanako-avatar-denim.png",
  "./icons/hanako-avatar-museum.png",
  "./icons/hanako-avatar-bakery.png",
  "./icons/hanako-avatar-resort.png",
  "./icons/hanako-avatar-studynight.png",
  "./icons/hanako-avatar-wamodern.png",
  "./icons/hanako-avatar-holiday.png",
  "./icons/hanako-avatar-perfume.png",
  "./icons/hanako-avatar-closet.png",
  "./icons/hanako-avatar-shopping.png",
  "./icons/hanako-avatar-mirror.png",
  "./icons/hanako-avatar-notebook.png",
  "./icons/hanako-avatar-heels.png",
  "./icons/hanako-avatar-jewelry.png",
  "./icons/hanako-avatar-teatime.png",
  "./icons/hanako-avatar-bouquet.png",
  "./icons/hanako-avatar-smartphone.png",
  "./icons/hanako-avatar-parasol.png",
  "./icons/hanako-avatar-sewing.png",
  "./icons/hanako-avatar-camera.png",
  "./icons/hanako-avatar-sunhat.png",
  "./icons/hanako-avatar-dessert.png",
  "./icons/hanako-avatar-parisienne.png",
  "./icons/hanako-avatar-picnic.png",
  "./icons/hanako-avatar-balletcore.png",
  "./icons/hanako-avatar-cinema.png",
  "./icons/hanako-avatar-ceramics.png",
  "./icons/hanako-avatar-gardening.png",
  "./icons/hanako-avatar-library.png",
  "./icons/hanako-avatar-seaside.png",
  "./icons/hanako-avatar-nightout.png",
  "./icons/hanako-avatar-ribbonlady.png",
  "./icons/hanako-avatar-vanitytray.png",
  "./icons/hanako-avatar-maryjanes.png",
  "./icons/hanako-avatar-ribboncardigan.png",
  "./icons/hanako-avatar-cafeplate.png",
  "./icons/hanako-avatar-charmbracelet.png",
  "./icons/hanako-avatar-royalgala.png",
  "./icons/hanako-avatar-yozakura.png",
  "./icons/hanako-avatar-moonlight.png",
  "./icons/hanako-avatar-anniversaryrose.png",
  "./icons/hanako-avatar-royalribbon.png",
  "./icons/hanako-avatar-grandgala.png",
  "./icons/hanako-avatar-sakurajewel.png",
  "./icons/hanako-avatar-legendteacher.png",
  "./icons/hanako-avatar-celestial.png",
  "./icons/hanako-avatar-ribbonresort.png",
  "./icons/hanako-avatar-marineswim.png",
  "./icons/hanako-avatar-jewelprincess.png",
  "./icons/icon-mint-192.png",
  "./icons/icon-mint-512.png",
  "./icons/icon-navy-192.png",
  "./icons/icon-navy-512.png",
  "./icons/icon-strawberry-192.png",
  "./icons/icon-strawberry-512.png",
  "./icons/icon-lemon-192.png",
  "./icons/icon-lemon-512.png",
  "./icons/icon-aqua-192.png",
  "./icons/icon-aqua-512.png",
  "./icons/icon-classic-192.png",
  "./icons/icon-classic-512.png",
  "./icons/icon-office-192.png",
  "./icons/icon-office-512.png",
  "./icons/icon-oshikatsu-192.png",
  "./icons/icon-oshikatsu-512.png",
  "./icons/icon-campus-192.png",
  "./icons/icon-campus-512.png",
  "./icons/icon-rainy-192.png",
  "./icons/icon-rainy-512.png",
  "./icons/icon-sakura-192.png",
  "./icons/icon-sakura-512.png",
  "./icons/icon-marine-192.png",
  "./icons/icon-marine-512.png",
  "./icons/icon-autumn-192.png",
  "./icons/icon-autumn-512.png",
  "./icons/icon-winter-192.png",
  "./icons/icon-winter-512.png",
  "./icons/icon-beauty-192.png",
  "./icons/icon-beauty-512.png",
  "./icons/icon-travelgirl-192.png",
  "./icons/icon-travelgirl-512.png",
  "./icons/icon-sporty-192.png",
  "./icons/icon-sporty-512.png",
  "./icons/icon-evening-192.png",
  "./icons/icon-evening-512.png",
  "./icons/icon-chocolate-192.png",
  "./icons/icon-chocolate-512.png",
  "./icons/icon-florist-192.png",
  "./icons/icon-florist-512.png",
  "./icons/icon-music-192.png",
  "./icons/icon-music-512.png",
  "./icons/icon-denim-192.png",
  "./icons/icon-denim-512.png",
  "./icons/icon-museum-192.png",
  "./icons/icon-museum-512.png",
  "./icons/icon-bakery-192.png",
  "./icons/icon-bakery-512.png",
  "./icons/icon-resort-192.png",
  "./icons/icon-resort-512.png",
  "./icons/icon-studynight-192.png",
  "./icons/icon-studynight-512.png",
  "./icons/icon-wamodern-192.png",
  "./icons/icon-wamodern-512.png",
  "./icons/icon-holiday-192.png",
  "./icons/icon-holiday-512.png",
  "./icons/icon-perfume-192.png",
  "./icons/icon-perfume-512.png",
  "./icons/icon-closet-192.png",
  "./icons/icon-closet-512.png",
  "./icons/icon-shopping-192.png",
  "./icons/icon-shopping-512.png",
  "./icons/icon-mirror-192.png",
  "./icons/icon-mirror-512.png",
  "./icons/icon-notebook-192.png",
  "./icons/icon-notebook-512.png",
  "./icons/icon-heels-192.png",
  "./icons/icon-heels-512.png",
  "./icons/icon-jewelry-192.png",
  "./icons/icon-jewelry-512.png",
  "./icons/icon-teatime-192.png",
  "./icons/icon-teatime-512.png",
  "./icons/icon-bouquet-192.png",
  "./icons/icon-bouquet-512.png",
  "./icons/icon-smartphone-192.png",
  "./icons/icon-smartphone-512.png",
  "./icons/icon-parasol-192.png",
  "./icons/icon-parasol-512.png",
  "./icons/icon-sewing-192.png",
  "./icons/icon-sewing-512.png",
  "./icons/icon-camera-192.png",
  "./icons/icon-camera-512.png",
  "./icons/icon-sunhat-192.png",
  "./icons/icon-sunhat-512.png",
  "./icons/icon-dessert-192.png",
  "./icons/icon-dessert-512.png",
  "./icons/icon-parisienne-192.png",
  "./icons/icon-parisienne-512.png",
  "./icons/icon-picnic-192.png",
  "./icons/icon-picnic-512.png",
  "./icons/icon-balletcore-192.png",
  "./icons/icon-balletcore-512.png",
  "./icons/icon-cinema-192.png",
  "./icons/icon-cinema-512.png",
  "./icons/icon-ceramics-192.png",
  "./icons/icon-ceramics-512.png",
  "./icons/icon-gardening-192.png",
  "./icons/icon-gardening-512.png",
  "./icons/icon-library-192.png",
  "./icons/icon-library-512.png",
  "./icons/icon-seaside-192.png",
  "./icons/icon-seaside-512.png",
  "./icons/icon-nightout-192.png",
  "./icons/icon-nightout-512.png",
  "./icons/icon-ribbonlady-192.png",
  "./icons/icon-ribbonlady-512.png",
  "./icons/icon-vanitytray-192.png",
  "./icons/icon-vanitytray-512.png",
  "./icons/icon-maryjanes-192.png",
  "./icons/icon-maryjanes-512.png",
  "./icons/icon-ribboncardigan-192.png",
  "./icons/icon-ribboncardigan-512.png",
  "./icons/icon-cafeplate-192.png",
  "./icons/icon-cafeplate-512.png",
  "./icons/icon-charmbracelet-192.png",
  "./icons/icon-charmbracelet-512.png",
  "./icons/icon-royalgala-192.png",
  "./icons/icon-royalgala-512.png",
  "./icons/icon-yozakura-192.png",
  "./icons/icon-yozakura-512.png",
  "./icons/icon-moonlight-192.png",
  "./icons/icon-moonlight-512.png",
  "./icons/icon-anniversaryrose-192.png",
  "./icons/icon-anniversaryrose-512.png",
  "./icons/icon-jewelprincess-192.png",
  "./icons/icon-jewelprincess-512.png",
  "./icons/hanako-avatar-colorpalette.png",
  "./icons/hanako-avatar-wardrobeaudit.png",
  "./icons/hanako-avatar-fitcheck.png",
  "./icons/hanako-avatar-shoeclinic.png",
  "./icons/hanako-avatar-accessorylab.png",
  "./icons/hanako-avatar-salehunter.png",
  "./icons/hanako-avatar-layering.png",
  "./icons/hanako-avatar-formalguest.png",
  "./icons/hanako-avatar-streetstyle.png",
  "./icons/hanako-avatar-creatorstudio.png",
  "./icons/hanako-avatar-ribbonmannequin.png",
  "./icons/hanako-avatar-styletablet.png",
  "./icons/hanako-avatar-magazinestack.png",
  "./icons/hanako-avatar-jewelhanger.png",
  "./icons/hanako-avatar-coordboard.png",
  "./icons/icon-colorpalette-192.png",
  "./icons/icon-colorpalette-512.png",
  "./icons/icon-wardrobeaudit-192.png",
  "./icons/icon-wardrobeaudit-512.png",
  "./icons/icon-fitcheck-192.png",
  "./icons/icon-fitcheck-512.png",
  "./icons/icon-shoeclinic-192.png",
  "./icons/icon-shoeclinic-512.png",
  "./icons/icon-accessorylab-192.png",
  "./icons/icon-accessorylab-512.png",
  "./icons/icon-salehunter-192.png",
  "./icons/icon-salehunter-512.png",
  "./icons/icon-layering-192.png",
  "./icons/icon-layering-512.png",
  "./icons/icon-formalguest-192.png",
  "./icons/icon-formalguest-512.png",
  "./icons/icon-streetstyle-192.png",
  "./icons/icon-streetstyle-512.png",
  "./icons/icon-creatorstudio-192.png",
  "./icons/icon-creatorstudio-512.png",
  "./icons/icon-ribbonmannequin-192.png",
  "./icons/icon-ribbonmannequin-512.png",
  "./icons/icon-styletablet-192.png",
  "./icons/icon-styletablet-512.png",
  "./icons/icon-magazinestack-192.png",
  "./icons/icon-magazinestack-512.png",
  "./icons/icon-jewelhanger-192.png",
  "./icons/icon-jewelhanger-512.png",
  "./icons/icon-coordboard-192.png",
  "./icons/icon-coordboard-512.png",
  "./icons/hanako-avatar-wavebalance.png",
  "./icons/hanako-avatar-petitebalance.png",
  "./icons/hanako-avatar-fabricexpert.png",
  "./icons/hanako-avatar-bagstylist.png",
  "./icons/hanako-avatar-travelpacking.png",
  "./icons/hanako-avatar-photoangle.png",
  "./icons/hanako-avatar-temperature.png",
  "./icons/hanako-avatar-datestyle.png",
  "./icons/hanako-avatar-fabriccare.png",
  "./icons/hanako-avatar-trendcheck.png",
  "./icons/icon-wavebalance-192.png",
  "./icons/icon-wavebalance-512.png",
  "./icons/icon-petitebalance-192.png",
  "./icons/icon-petitebalance-512.png",
  "./icons/icon-fabricexpert-192.png",
  "./icons/icon-fabricexpert-512.png",
  "./icons/icon-bagstylist-192.png",
  "./icons/icon-bagstylist-512.png",
  "./icons/icon-travelpacking-192.png",
  "./icons/icon-travelpacking-512.png",
  "./icons/icon-photoangle-192.png",
  "./icons/icon-photoangle-512.png",
  "./icons/icon-temperature-192.png",
  "./icons/icon-temperature-512.png",
  "./icons/icon-datestyle-192.png",
  "./icons/icon-datestyle-512.png",
  "./icons/icon-fabriccare-192.png",
  "./icons/icon-fabriccare-512.png",
  "./icons/icon-trendcheck-192.png",
  "./icons/icon-trendcheck-512.png",
  "./icons/nav-home.svg",
  "./icons/nav-products.svg",
  "./icons/nav-room.svg",
  "./icons/nav-coordinate.svg",
  "./icons/nav-generator.svg",
  "./icons/nav-calendar.svg",
  "./icons/nav-connections.svg",
  "./icons/nav-analytics.svg",
];

const CORE_SHELL = [
  "./",
  "./index.html",
    "./styles.css?v=187",
    "./app.js?v=187",
    "./cloud-sync.js?v=187",
    "./ops-engine.js?v=187",
    "./ops-phase2-engine.js?v=187",
    "./ops-phase3-engine.js?v=187",
    "./ops-phase4-engine.js?v=187",
    "./room-review-generator.js?v=187",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      await cache.addAll(CORE_SHELL);
      const optionalAssets = APP_SHELL.filter((asset) => !CORE_SHELL.includes(asset));
      await Promise.allSettled(optionalAssets.map((asset) => cache.add(asset)));
    }),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => !PERSISTENT_CACHES.has(key)).map((key) => caches.delete(key)))),
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;

  const url = new URL(event.request.url);
  if (url.pathname.endsWith("/config.js") || url.pathname.endsWith("/version.json") || url.pathname.endsWith("/update.html")) {
    event.respondWith(fetch(event.request));
    return;
  }

  const isAppCode = url.origin === self.location.origin && (
    event.request.mode === "navigate"
    || url.pathname.endsWith("/index.html")
    || url.pathname.endsWith("/app.js")
    || url.pathname.endsWith("/styles.css")
    || url.pathname.endsWith("/cloud-sync.js")
    || url.pathname.endsWith("/ops-engine.js")
    || url.pathname.endsWith("/ops-phase2-engine.js")
    || url.pathname.endsWith("/ops-phase3-engine.js")
    || url.pathname.endsWith("/ops-phase4-engine.js")
    || url.pathname.endsWith("/room-review-generator.js")
    || url.pathname.endsWith("/sw.js")
  );

  if (isAppCode) {
    event.respondWith(
      fetch(event.request, { cache: "no-store" })
        .then((response) => {
          if (!response.ok) throw new Error(`更新ファイルを取得できませんでした (${response.status})`);
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
          return response;
        })
        .catch(() => caches.match(event.request).then((cached) => cached || caches.match("./index.html"))),
    );
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;

      return fetch(event.request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
          return response;
        })
        .catch(() => caches.match("./index.html"));
    }),
  );
});
